# Site settings
title: Tiny Jiang
email: jhjiang888@gmail.com
description: "HangZhou, China"
baseurl: ""
url: "http://www.tinyjiang.com"

# Build settings
markdown: kramdown
permalink: pretty

highlighter: pygments
